import type { CatalogExercise } from './contracts';

export const exercises: CatalogExercise[] = [
  {
    id: 'ex_bench_barbell',
    name: 'Barbell Bench Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'barbell',
    movement: 'compound',
    laterality: 'bilateral',
  },
  {
    id: 'ex_incline_db',
    name: 'Incline Dumbbell Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: 'dumbbell',
    movement: 'compound',
    laterality: 'unilateral',
  },
  {
    id: 'ex_barbell_row',
    name: 'Barbell Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'barbell',
    movement: 'compound',
    laterality: 'bilateral',
  },
  {
    id: 'ex_ohp',
    name: 'Overhead Press',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'barbell',
    movement: 'compound',
    laterality: 'bilateral',
  },
  {
    id: 'ex_squat',
    name: 'Back Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'barbell',
    movement: 'compound',
    laterality: 'bilateral',
  },
  {
    id: 'ex_deadlift',
    name: 'Deadlift',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['back', 'glutes'],
    equipment: 'barbell',
    movement: 'compound',
    laterality: 'bilateral',
  },
  {
    id: 'ex_bicep_curl',
    name: 'Dumbbell Bicep Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    movement: 'isolation',
    laterality: 'unilateral',
  },
  {
    id: 'ex_tricep_pushdown',
    name: 'Triceps Rope Pushdown',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'cable',
    movement: 'isolation',
    laterality: 'either',
  },

  // ---------------- New additions below ----------------

  {
    id: 'ex_lat_pulldown',
    name: 'Lat Pulldown',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'cable',
    movement: 'compound',
    laterality: 'bilateral',
  },
  {
    id: 'ex_pull_up',
    name: 'Pull-Up',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'bodyweight',
    movement: 'compound',
    laterality: 'bilateral',
  },
  {
    id: 'ex_seated_cable_row',
    name: 'Seated Cable Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'cable',
    movement: 'compound',
    laterality: 'bilateral',
  },
  {
    id: 'ex_one_arm_db_row',
    name: 'One-Arm Dumbbell Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'dumbbell',
    movement: 'compound',
    laterality: 'unilateral',
  },
  {
    id: 'ex_tbar_row_machine',
    name: 'Chest-Supported T-Bar Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'machine',
    movement: 'compound',
    laterality: 'bilateral',
  },

  {
    id: 'ex_incline_barbell_press',
    name: 'Incline Barbell Bench Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: 'barbell',
    movement: 'compound',
    laterality: 'bilateral',
  },
  {
    id: 'ex_cable_fly',
    name: 'Cable Chest Fly',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders'],
    equipment: 'cable',
    movement: 'isolation',
    laterality: 'bilateral',
  },
  {
    id: 'ex_incline_db_fly',
    name: 'Incline Dumbbell Fly',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders'],
    equipment: 'dumbbell',
    movement: 'isolation',
    laterality: 'either',
  },

  {
    id: 'ex_lateral_raise_db',
    name: 'Dumbbell Lateral Raise',
    primaryMuscle: 'shoulders',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    movement: 'isolation',
    laterality: 'either',
  },
  {
    id: 'ex_lateral_raise_cable',
    name: 'Cable Lateral Raise',
    primaryMuscle: 'shoulders',
    secondaryMuscles: [],
    equipment: 'cable',
    movement: 'isolation',
    laterality: 'unilateral',
  },
  {
    id: 'ex_face_pull',
    name: 'Face Pull',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['back'],
    equipment: 'cable',
    movement: 'isolation',
    laterality: 'either',
  },
  {
    id: 'ex_rear_delt_fly_db',
    name: 'Bent-Over Rear Delt Fly',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['back'],
    equipment: 'dumbbell',
    movement: 'isolation',
    laterality: 'either',
  },
  {
    id: 'ex_arnold_press',
    name: 'Arnold Press',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'dumbbell',
    movement: 'compound',
    laterality: 'bilateral',
  },

  {
    id: 'ex_rdl_barbell',
    name: 'Romanian Deadlift',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes', 'back'],
    equipment: 'barbell',
    movement: 'compound',
    laterality: 'bilateral',
  },
  {
    id: 'ex_hip_thrust_barbell',
    name: 'Barbell Hip Thrust',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings'],
    equipment: 'barbell',
    movement: 'compound',
    laterality: 'bilateral',
  },
  {
    id: 'ex_leg_press',
    name: 'Leg Press',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'machine',
    movement: 'compound',
    laterality: 'bilateral',
  },
  {
    id: 'ex_leg_extension',
    name: 'Leg Extension',
    primaryMuscle: 'quads',
    secondaryMuscles: [],
    equipment: 'machine',
    movement: 'isolation',
    laterality: 'bilateral',
  },
  {
    id: 'ex_leg_curl',
    name: 'Seated Leg Curl',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: [],
    equipment: 'machine',
    movement: 'isolation',
    laterality: 'bilateral',
  },
  {
    id: 'ex_bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'dumbbell',
    movement: 'compound',
    laterality: 'unilateral',
  },
  {
    id: 'ex_front_squat',
    name: 'Front Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'barbell',
    movement: 'compound',
    laterality: 'bilateral',
  },

  {
    id: 'ex_close_grip_bench',
    name: 'Close-Grip Bench Press',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: 'barbell',
    movement: 'compound',
    laterality: 'bilateral',
  },
  {
    id: 'ex_skull_crushers',
    name: 'Lying EZ-Bar Triceps Extension (Skull Crushers)',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'barbell',
    movement: 'isolation',
    laterality: 'bilateral',
  },
  {
    id: 'ex_oh_triceps_ext_cable',
    name: 'Overhead Triceps Extension (Rope)',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'cable',
    movement: 'isolation',
    laterality: 'either',
  },

  {
    id: 'ex_hammer_curl',
    name: 'Hammer Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    movement: 'isolation',
    laterality: 'unilateral',
  },
  {
    id: 'ex_preacher_curl_ez',
    name: 'Preacher Curl (EZ-Bar)',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'barbell',
    movement: 'isolation',
    laterality: 'bilateral',
  }
];

