import type { CatalogExercise } from './contracts';

type MuscleTarget = NonNullable<CatalogExercise['muscleTargets']>[number];
type Part = MuscleTarget['part'];
type Role = MuscleTarget['role'];

// These are exercise-selection estimates, not measurements of activation or growth.
// Shared involvement does not imply equal loading; a bias never means isolation.
// Keep IDs stable because routines and historical snapshots reference them.
function shared(role: Role, ...parts: Part[]): MuscleTarget[] {
  return parts.map(part => ({ part, role, emphasis: 'shared' }));
}
const primary = (...parts: Part[]) => shared('primary', ...parts);
const secondary = (...parts: Part[]) => shared('secondary', ...parts);
const biased = (...parts: Part[]): MuscleTarget[] =>
  parts.map(part => ({ part, role: 'primary', emphasis: 'biased' }));

const elbowFlexors = (role: Role = 'primary') =>
  shared(role, 'biceps_long_head', 'biceps_short_head', 'brachialis');
const triceps = (role: Role = 'primary') =>
  shared(role, 'triceps_long_head', 'triceps_lateral_head', 'triceps_medial_head');
const overheadTriceps = () => [
  ...biased('triceps_long_head'),
  ...primary('triceps_lateral_head', 'triceps_medial_head'),
];
const vasti = () => primary('vastus_lateralis', 'vastus_medialis', 'vastus_intermedius');
const secondaryVasti = () => secondary('vastus_lateralis', 'vastus_medialis', 'vastus_intermedius');
const hipHamstrings = (role: Role = 'primary') =>
  shared(role, 'biceps_femoris_long_head', 'semitendinosus', 'semimembranosus');
const kneeHamstrings = () => [...hipHamstrings(), ...primary('biceps_femoris_short_head')];
const adductors = () =>
  primary('adductor_magnus', 'adductor_longus', 'adductor_brevis', 'gracilis', 'pectineus');

// See ../CATALOG_NOTES.md for scope, interpretation and research references.
export const exercises: CatalogExercise[] = [

  {
    id: 'ex_bench_barbell',
    name: 'Barbell Bench Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'barbell', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...biased('pectoralis_sternocostal'), ...primary('pectoralis_clavicular'), ...triceps('secondary'), ...secondary('deltoid_anterior')],
    biasNotes: 'A flat press emphasizes the sternocostal chest while the clavicular head also contributes.',
  },
  {
    id: 'ex_incline_db',
    name: 'Incline Dumbbell Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: 'dumbbell', movement: 'compound', laterality: 'either',
    muscleTargets: [...biased('pectoralis_clavicular'), ...primary('pectoralis_sternocostal'), ...secondary('deltoid_anterior'), ...triceps('secondary')],
    biasNotes: 'An incline shifts chest emphasis toward the clavicular head; both chest heads still contribute.',
  },
  {
    id: 'ex_barbell_row',
    name: 'Barbell Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'shoulders'],
    equipment: 'barbell', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...primary('latissimus_dorsi', 'trapezius_middle', 'rhomboids', 'teres_major'), ...elbowFlexors('secondary'), ...secondary('deltoid_posterior')],
  },
  {
    id: 'ex_ohp',
    name: 'Overhead Press',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'barbell', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...biased('deltoid_anterior'), ...primary('deltoid_lateral'), ...triceps('secondary')],
  },
  {
    id: 'ex_squat',
    name: 'Back Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'adductors'],
    equipment: 'barbell', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...vasti(), ...secondary('gluteus_maximus', 'adductor_magnus')],
    biasNotes: 'Emphasizes the vasti with glute and adductor assistance. Squats are not counted as targeted hamstring work.',
  },
  {
    id: 'ex_deadlift',
    name: 'Deadlift',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['back', 'glutes', 'quads'],
    equipment: 'barbell', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...hipHamstrings(), ...secondary('gluteus_maximus', 'erector_spinae'), ...secondaryVasti()],
    biasNotes: 'A full-body hinge with meaningful hamstring, glute, spinal erector and quad involvement; no single hamstring head is isolated.',
  },
  {
    id: 'ex_bicep_curl',
    name: 'Dumbbell Bicep Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'dumbbell', movement: 'isolation', laterality: 'unilateral',
    muscleTargets: [...elbowFlexors()],
    biasNotes: 'Both biceps heads and the brachialis share elbow flexion; this variation is not assigned an isolated long- or short-head bias.',
  },
  {
    id: 'ex_tricep_pushdown',
    name: 'Triceps Rope Pushdown',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'cable', movement: 'isolation', laterality: 'either',
    muscleTargets: [...triceps()],
    biasNotes: 'All three triceps heads extend the elbow; a pushdown is not assigned an isolated lateral- or medial-head bias.',
  },
  {
    id: 'ex_lat_pulldown',
    name: 'Lat Pulldown',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'cable', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...biased('latissimus_dorsi'), ...primary('teres_major', 'trapezius_lower'), ...elbowFlexors('secondary')],
    biasNotes: 'The lats are tracked as one muscle; grip choice is not used to invent separate upper- or lower-lat targets.',
  },
  {
    id: 'ex_pull_up',
    name: 'Pull-Up',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'bodyweight', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...biased('latissimus_dorsi'), ...primary('teres_major', 'trapezius_lower'), ...elbowFlexors('secondary')],
    biasNotes: 'The lats are tracked as one muscle; grip choice is not used to invent separate upper- or lower-lat targets.',
  },
  {
    id: 'ex_seated_cable_row',
    name: 'Seated Cable Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'shoulders'],
    equipment: 'cable', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...primary('latissimus_dorsi', 'trapezius_middle', 'rhomboids', 'teres_major'), ...elbowFlexors('secondary'), ...secondary('deltoid_posterior')],
  },
  {
    id: 'ex_one_arm_db_row',
    name: 'One-Arm Dumbbell Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'shoulders'],
    equipment: 'dumbbell', movement: 'compound', laterality: 'unilateral',
    muscleTargets: [...primary('latissimus_dorsi', 'trapezius_middle', 'rhomboids', 'teres_major'), ...elbowFlexors('secondary'), ...secondary('deltoid_posterior')],
  },
  {
    id: 'ex_tbar_row_machine',
    name: 'Chest-Supported T-Bar Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'shoulders'],
    equipment: 'machine', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...primary('latissimus_dorsi', 'trapezius_middle', 'rhomboids', 'teres_major'), ...elbowFlexors('secondary'), ...secondary('deltoid_posterior')],
  },
  {
    id: 'ex_incline_barbell_press',
    name: 'Incline Barbell Bench Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: 'barbell', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...biased('pectoralis_clavicular'), ...primary('pectoralis_sternocostal'), ...secondary('deltoid_anterior'), ...triceps('secondary')],
    biasNotes: 'An incline shifts chest emphasis toward the clavicular head; both chest heads still contribute.',
  },
  {
    id: 'ex_cable_fly',
    name: 'Cable Chest Fly',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders'],
    equipment: 'cable', movement: 'isolation', laterality: 'bilateral',
    muscleTargets: [...primary('pectoralis_clavicular', 'pectoralis_sternocostal'), ...secondary('deltoid_anterior')],
    biasNotes: 'A standard chest-height fly shares work across both chest heads; cable height and arm path can change the emphasis.',
  },
  {
    id: 'ex_incline_db_fly',
    name: 'Incline Dumbbell Fly',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders'],
    equipment: 'dumbbell', movement: 'isolation', laterality: 'either',
    muscleTargets: [...biased('pectoralis_clavicular'), ...primary('pectoralis_sternocostal'), ...secondary('deltoid_anterior')],
    biasNotes: 'The incline favors a clavicular chest emphasis, without isolating that head.',
  },
  {
    id: 'ex_lateral_raise_db',
    name: 'Dumbbell Lateral Raise',
    primaryMuscle: 'shoulders',
    secondaryMuscles: [],
    equipment: 'dumbbell', movement: 'isolation', laterality: 'either',
    muscleTargets: [...biased('deltoid_lateral')],
  },
  {
    id: 'ex_lateral_raise_cable',
    name: 'Cable Lateral Raise',
    primaryMuscle: 'shoulders',
    secondaryMuscles: [],
    equipment: 'cable', movement: 'isolation', laterality: 'unilateral',
    muscleTargets: [...biased('deltoid_lateral')],
  },
  {
    id: 'ex_face_pull',
    name: 'Face Pull',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['back', 'rotator cuff'],
    equipment: 'cable', movement: 'isolation', laterality: 'either',
    muscleTargets: [...biased('deltoid_posterior'), ...secondary('trapezius_middle', 'rhomboids'), ...secondary('infraspinatus', 'teres_minor')],
    biasNotes: 'Rear delts and scapular retractors work together; the external-rotation finish also involves the external rotators.',
  },
  {
    id: 'ex_rear_delt_fly_db',
    name: 'Bent-Over Rear Delt Fly',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['back'],
    equipment: 'dumbbell', movement: 'isolation', laterality: 'either',
    muscleTargets: [...biased('deltoid_posterior'), ...secondary('trapezius_middle', 'rhomboids')],
  },
  {
    id: 'ex_arnold_press',
    name: 'Arnold Press',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'dumbbell', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...biased('deltoid_anterior'), ...primary('deltoid_lateral'), ...triceps('secondary')],
  },
  {
    id: 'ex_rdl_barbell',
    name: 'Romanian Deadlift',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes', 'back'],
    equipment: 'barbell', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...hipHamstrings(), ...secondary('gluteus_maximus', 'erector_spinae')],
    biasNotes: 'Hip extension loads the long head of biceps femoris, semitendinosus and semimembranosus; the short head does not cross the hip.',
  },
  {
    id: 'ex_hip_thrust_barbell',
    name: 'Barbell Hip Thrust',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings'],
    equipment: 'barbell', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...biased('gluteus_maximus'), ...hipHamstrings('secondary')],
    biasNotes: 'Emphasizes hip extension by gluteus maximus; hamstrings assist without an isolated head bias.',
  },
  {
    id: 'ex_leg_press',
    name: 'Leg Press',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'adductors'],
    equipment: 'machine', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...vasti(), ...secondary('gluteus_maximus', 'adductor_magnus')],
    biasNotes: 'Emphasizes the vasti with glute and adductor assistance. Foot placement does not isolate a particular vastus head.',
  },
  {
    id: 'ex_leg_extension',
    name: 'Leg Extension',
    primaryMuscle: 'quads',
    secondaryMuscles: [],
    equipment: 'machine', movement: 'isolation', laterality: 'bilateral',
    muscleTargets: [...biased('rectus_femoris'), ...vasti()],
    biasNotes: 'All four quadriceps muscles extend the knee. Leg extensions add direct rectus femoris work that squat patterns can underload.',
  },
  {
    id: 'ex_leg_curl',
    name: 'Seated Leg Curl',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: [],
    equipment: 'machine', movement: 'isolation', laterality: 'bilateral',
    muscleTargets: [...kneeHamstrings()],
    biasNotes: 'Knee flexion trains all four tracked hamstring parts, including the biceps femoris short head; sitting lengthens the muscles that also cross the hip.',
  },
  {
    id: 'ex_bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'adductors'],
    equipment: 'dumbbell', movement: 'compound', laterality: 'unilateral',
    muscleTargets: [...vasti(), ...secondary('gluteus_maximus', 'gluteus_medius', 'adductor_magnus')],
    biasNotes: 'Stride, torso position and depth change the quad/glute balance; no individual vastus head is isolated.',
  },
  {
    id: 'ex_front_squat',
    name: 'Front Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'adductors'],
    equipment: 'barbell', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...vasti(), ...secondary('gluteus_maximus', 'adductor_magnus')],
    biasNotes: 'Emphasizes the vasti with glute and adductor assistance. Squats are not counted as targeted hamstring work.',
  },
  {
    id: 'ex_close_grip_bench',
    name: 'Close-Grip Bench Press',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: 'barbell', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...triceps(), ...secondary('pectoralis_clavicular', 'pectoralis_sternocostal', 'deltoid_anterior')],
    biasNotes: 'A close grip increases the elbow-extension demand; all triceps heads contribute.',
  },
  {
    id: 'ex_skull_crushers',
    name: 'Lying EZ-Bar Triceps Extension (Skull Crushers)',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'barbell', movement: 'isolation', laterality: 'bilateral',
    muscleTargets: [...triceps()],
    biasNotes: 'All three triceps heads contribute. Shoulder position and how far the bar travels behind the head affect long-head length.',
  },
  {
    id: 'ex_oh_triceps_ext_cable',
    name: 'Overhead Triceps Extension (Rope)',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'cable', movement: 'isolation', laterality: 'either',
    muscleTargets: [...overheadTriceps()],
    biasNotes: 'The overhead arm position lengthens and emphasizes the triceps long head; lateral and medial heads still contribute.',
  },
  {
    id: 'ex_hammer_curl',
    name: 'Hammer Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: 'dumbbell', movement: 'isolation', laterality: 'unilateral',
    muscleTargets: [...elbowFlexors(), ...secondary('brachioradialis')],
    biasNotes: 'A neutral grip includes substantial brachialis and brachioradialis work; both biceps heads remain involved.',
  },
  {
    id: 'ex_preacher_curl_ez',
    name: 'Preacher Curl (EZ-Bar)',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'barbell', movement: 'isolation', laterality: 'bilateral',
    muscleTargets: [...elbowFlexors()],
    biasNotes: 'Both biceps heads and the brachialis share elbow flexion; this variation is not assigned an isolated long- or short-head bias.',
  },
  {
    id: 'ex_machine_press',
    name: 'Machine Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'machine', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...biased('pectoralis_sternocostal'), ...primary('pectoralis_clavicular'), ...triceps('secondary'), ...secondary('deltoid_anterior')],
  },
  {
    id: 'ex_preacher_curl_30',
    name: '30° Preacher Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'dumbbell', movement: 'isolation', laterality: 'unilateral',
    muscleTargets: [...elbowFlexors()],
    biasNotes: 'Both biceps heads and the brachialis share elbow flexion; this variation is not assigned an isolated long- or short-head bias.',
  },
  {
    id: 'ex_preacher_curl_60',
    name: '60° Preacher Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'dumbbell', movement: 'isolation', laterality: 'unilateral',
    muscleTargets: [...elbowFlexors()],
    biasNotes: 'Both biceps heads and the brachialis share elbow flexion; this variation is not assigned an isolated long- or short-head bias.',
  },
  {
    id: 'ex_jm_press_barbell',
    name: 'JM Press (Barbell)',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['chest'],
    equipment: 'barbell', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...triceps(), ...secondary('pectoralis_sternocostal', 'pectoralis_clavicular')],
  },
  {
    id: 'ex_cuffed_extensions',
    name: 'Cuffed Extensions',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'cable', movement: 'isolation', laterality: 'either',
    muscleTargets: [...triceps()],
    biasNotes: 'The cuff alone does not establish a head bias; all triceps heads are tracked unless an overhead variation is selected.',
  },
  {
    id: 'ex_anterior_delt_raise_cable',
    name: 'Anterior Delt Raise (Cable)',
    primaryMuscle: 'shoulders',
    secondaryMuscles: [],
    equipment: 'cable', movement: 'isolation', laterality: 'unilateral',
    muscleTargets: [...biased('deltoid_anterior')],
  },
  {
    id: 'ex_bench_db',
    name: 'Dumbbell Bench Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'dumbbell', movement: 'compound', laterality: 'either',
    muscleTargets: [...biased('pectoralis_sternocostal'), ...primary('pectoralis_clavicular'), ...triceps('secondary'), ...secondary('deltoid_anterior')],
  },
  {
    id: 'ex_push_up',
    name: 'Push-Up',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'bodyweight', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...biased('pectoralis_sternocostal'), ...primary('pectoralis_clavicular'), ...triceps('secondary'), ...secondary('deltoid_anterior')],
  },
  {
    id: 'ex_chest_dip',
    name: 'Chest Dip',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'bodyweight', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...biased('pectoralis_sternocostal'), ...primary('pectoralis_clavicular'), ...triceps('secondary'), ...secondary('deltoid_anterior')],
    biasNotes: 'A forward-leaning dip emphasizes sternocostal chest with triceps and anterior delts assisting.',
  },
  {
    id: 'ex_pec_deck',
    name: 'Pec Deck Fly',
    primaryMuscle: 'chest',
    secondaryMuscles: [],
    equipment: 'machine', movement: 'isolation', laterality: 'bilateral',
    muscleTargets: [...primary('pectoralis_clavicular', 'pectoralis_sternocostal')],
  },
  {
    id: 'ex_decline_bench',
    name: 'Decline Barbell Bench Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'barbell', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...biased('pectoralis_sternocostal'), ...primary('pectoralis_clavicular'), ...triceps('secondary'), ...secondary('deltoid_anterior')],
    biasNotes: 'A decline press emphasizes the sternocostal region; the lower chest is not treated as a separate anatomical head.',
  },
  {
    id: 'ex_chin_up',
    name: 'Chin-Up',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'bodyweight', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...biased('latissimus_dorsi'), ...primary('teres_major', 'trapezius_lower'), ...elbowFlexors('secondary')],
  },
  {
    id: 'ex_straight_arm_pulldown',
    name: 'Straight-Arm Cable Pulldown',
    primaryMuscle: 'back',
    secondaryMuscles: [],
    equipment: 'cable', movement: 'isolation', laterality: 'bilateral',
    muscleTargets: [...biased('latissimus_dorsi'), ...primary('teres_major')],
    biasNotes: 'Shoulder extension emphasizes the lats and teres major without assigning an upper- or lower-lat subdivision.',
  },
  {
    id: 'ex_machine_row',
    name: 'Seated Machine Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'shoulders'],
    equipment: 'machine', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...primary('latissimus_dorsi', 'trapezius_middle', 'rhomboids', 'teres_major'), ...elbowFlexors('secondary'), ...secondary('deltoid_posterior')],
  },
  {
    id: 'ex_shrug_db',
    name: 'Dumbbell Shrug',
    primaryMuscle: 'back',
    secondaryMuscles: [],
    equipment: 'dumbbell', movement: 'isolation', laterality: 'bilateral',
    muscleTargets: [...biased('trapezius_upper')],
  },
  {
    id: 'ex_back_extension',
    name: '45° Back Extension',
    primaryMuscle: 'back',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'bodyweight', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...biased('erector_spinae'), ...secondary('gluteus_maximus'), ...hipHamstrings('secondary')],
    biasNotes: 'Spinal erectors resist trunk flexion while the glutes and hip-crossing hamstrings extend the hips; technique changes their relative contribution.',
  },
  {
    id: 'ex_prone_y_raise',
    name: 'Prone Y Raise',
    primaryMuscle: 'back',
    secondaryMuscles: ['shoulders'],
    equipment: 'dumbbell', movement: 'isolation', laterality: 'bilateral',
    muscleTargets: [...biased('trapezius_lower'), ...primary('trapezius_middle'), ...secondary('deltoid_posterior')],
    biasNotes: 'The overhead Y arm path emphasizes the lower trapezius during scapular control.',
  },
  {
    id: 'ex_seated_db_press',
    name: 'Seated Dumbbell Shoulder Press',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'dumbbell', movement: 'compound', laterality: 'either',
    muscleTargets: [...biased('deltoid_anterior'), ...primary('deltoid_lateral'), ...triceps('secondary')],
  },
  {
    id: 'ex_machine_shoulder_press',
    name: 'Machine Shoulder Press',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'machine', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...biased('deltoid_anterior'), ...primary('deltoid_lateral'), ...triceps('secondary')],
  },
  {
    id: 'ex_reverse_pec_deck',
    name: 'Reverse Pec Deck',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['back'],
    equipment: 'machine', movement: 'isolation', laterality: 'bilateral',
    muscleTargets: [...biased('deltoid_posterior'), ...secondary('trapezius_middle', 'rhomboids')],
  },
  {
    id: 'ex_rear_delt_fly_cable',
    name: 'Cable Rear Delt Fly',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['back'],
    equipment: 'cable', movement: 'isolation', laterality: 'either',
    muscleTargets: [...biased('deltoid_posterior'), ...secondary('trapezius_middle', 'rhomboids')],
  },
  {
    id: 'ex_front_raise_db',
    name: 'Dumbbell Front Raise',
    primaryMuscle: 'shoulders',
    secondaryMuscles: [],
    equipment: 'dumbbell', movement: 'isolation', laterality: 'either',
    muscleTargets: [...biased('deltoid_anterior')],
  },
  {
    id: 'ex_external_rotation_cable',
    name: 'Cable External Rotation',
    primaryMuscle: 'rotator cuff',
    secondaryMuscles: [],
    equipment: 'cable', movement: 'isolation', laterality: 'unilateral',
    muscleTargets: [...biased('infraspinatus', 'teres_minor')],
    biasNotes: 'External rotation emphasizes infraspinatus and teres minor together; neither is isolated.',
  },
  {
    id: 'ex_internal_rotation_cable',
    name: 'Cable Internal Rotation',
    primaryMuscle: 'rotator cuff',
    secondaryMuscles: [],
    equipment: 'cable', movement: 'isolation', laterality: 'unilateral',
    muscleTargets: [...biased('subscapularis')],
    biasNotes: 'Subscapularis is the tracked internal rotator; keep this as a controlled shoulder-rotation exercise.',
  },
  {
    id: 'ex_external_rotation_db',
    name: 'Side-Lying Dumbbell External Rotation',
    primaryMuscle: 'rotator cuff',
    secondaryMuscles: [],
    equipment: 'dumbbell', movement: 'isolation', laterality: 'unilateral',
    muscleTargets: [...biased('infraspinatus', 'teres_minor')],
  },
  {
    id: 'ex_scaption_db',
    name: 'Dumbbell Scaption (Full Can)',
    primaryMuscle: 'rotator cuff',
    secondaryMuscles: ['shoulders'],
    equipment: 'dumbbell', movement: 'isolation', laterality: 'either',
    muscleTargets: [...biased('supraspinatus'), ...secondary('deltoid_anterior', 'deltoid_lateral')],
    biasNotes: 'Raising the arms in the scapular plane with thumbs up trains supraspinatus alongside the deltoids; it does not isolate the cuff.',
  },
  {
    id: 'ex_barbell_curl',
    name: 'Barbell Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'barbell', movement: 'isolation', laterality: 'bilateral',
    muscleTargets: [...elbowFlexors()],
    biasNotes: 'Both biceps heads and the brachialis share elbow flexion; this variation is not assigned an isolated long- or short-head bias.',
  },
  {
    id: 'ex_incline_db_curl',
    name: 'Incline Dumbbell Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'dumbbell', movement: 'isolation', laterality: 'either',
    muscleTargets: [...elbowFlexors()],
    biasNotes: 'The shoulder-extended position changes biceps length; both heads are tracked without claiming selective long-head isolation.',
  },
  {
    id: 'ex_cable_curl',
    name: 'Cable Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'cable', movement: 'isolation', laterality: 'either',
    muscleTargets: [...elbowFlexors()],
    biasNotes: 'Both biceps heads and the brachialis share elbow flexion; this variation is not assigned an isolated long- or short-head bias.',
  },
  {
    id: 'ex_concentration_curl',
    name: 'Concentration Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'dumbbell', movement: 'isolation', laterality: 'unilateral',
    muscleTargets: [...elbowFlexors()],
    biasNotes: 'Both biceps heads and the brachialis share elbow flexion; this variation is not assigned an isolated long- or short-head bias.',
  },
  {
    id: 'ex_wrist_curl',
    name: 'Dumbbell Wrist Curl',
    primaryMuscle: 'forearms',
    secondaryMuscles: [],
    equipment: 'dumbbell', movement: 'isolation', laterality: 'either',
    muscleTargets: [...biased('wrist_flexors')],
  },
  {
    id: 'ex_reverse_wrist_curl',
    name: 'Dumbbell Reverse Wrist Curl',
    primaryMuscle: 'forearms',
    secondaryMuscles: [],
    equipment: 'dumbbell', movement: 'isolation', laterality: 'either',
    muscleTargets: [...biased('wrist_extensors')],
  },
  {
    id: 'ex_reverse_curl',
    name: 'EZ-Bar Reverse Curl',
    primaryMuscle: 'forearms',
    secondaryMuscles: ['biceps'],
    equipment: 'barbell', movement: 'isolation', laterality: 'bilateral',
    muscleTargets: [...biased('brachioradialis'), ...elbowFlexors('secondary')],
    biasNotes: 'A pronated grip makes brachioradialis a useful focus; brachialis and both biceps heads also flex the elbow.',
  },
  {
    id: 'ex_oh_triceps_ext_db',
    name: 'Overhead Dumbbell Triceps Extension',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'dumbbell', movement: 'isolation', laterality: 'either',
    muscleTargets: [...overheadTriceps()],
    biasNotes: 'The overhead position lengthens the triceps long head while all three heads extend the elbow.',
  },
  {
    id: 'ex_triceps_pushdown_bar',
    name: 'Straight-Bar Triceps Pushdown',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'cable', movement: 'isolation', laterality: 'bilateral',
    muscleTargets: [...triceps()],
    biasNotes: 'All three heads contribute; changing the attachment does not establish an isolated lateral- or medial-head bias.',
  },
  {
    id: 'ex_triceps_extension_machine',
    name: 'Machine Triceps Extension',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'machine', movement: 'isolation', laterality: 'bilateral',
    muscleTargets: [...triceps()],
  },
  {
    id: 'ex_step_up',
    name: 'Step Ups',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes'],
    equipment: 'dumbbell', movement: 'compound', laterality: 'unilateral',
    muscleTargets: [...vasti(), ...primary('rectus_femoris'), ...secondary('gluteus_maximus', 'gluteus_medius')],
    biasNotes: 'Step height and torso angle change the quad/glute balance. Gluteus medius helps control the pelvis on the working leg; no individual quad head is isolated.',
  },
  {
    id: 'ex_goblet_squat',
    name: 'Goblet Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'adductors'],
    equipment: 'dumbbell', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...vasti(), ...secondary('gluteus_maximus', 'adductor_magnus')],
    biasNotes: 'Emphasizes the vasti with glute and adductor assistance. Squats are not counted as targeted hamstring work.',
  },
  {
    id: 'ex_hack_squat',
    name: 'Hack Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'adductors'],
    equipment: 'machine', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...vasti(), ...secondary('gluteus_maximus', 'adductor_magnus')],
    biasNotes: 'Trains the vasti with glute and adductor assistance; stance changes are not assigned isolated inner- or outer-quad targets.',
  },
  {
    id: 'ex_walking_lunge',
    name: 'Walking Lunge',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'adductors'],
    equipment: 'dumbbell', movement: 'compound', laterality: 'unilateral',
    muscleTargets: [...vasti(), ...secondary('gluteus_maximus', 'gluteus_medius', 'adductor_magnus')],
  },
  {
    id: 'ex_reverse_lunge',
    name: 'Reverse Lunge',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'adductors'],
    equipment: 'dumbbell', movement: 'compound', laterality: 'unilateral',
    muscleTargets: [...vasti(), ...secondary('gluteus_maximus', 'gluteus_medius', 'adductor_magnus')],
  },
  {
    id: 'ex_smith_squat',
    name: 'Smith Machine Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'adductors'],
    equipment: 'machine', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...vasti(), ...secondary('gluteus_maximus', 'adductor_magnus')],
    biasNotes: 'Emphasizes the vasti with glute and adductor assistance. Squats are not counted as targeted hamstring work.',
  },
  {
    id: 'ex_lying_leg_curl',
    name: 'Lying Leg Curl',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: [],
    equipment: 'machine', movement: 'isolation', laterality: 'bilateral',
    muscleTargets: [...kneeHamstrings()],
    biasNotes: 'Knee flexion includes both biceps femoris heads, semitendinosus and semimembranosus.',
  },
  {
    id: 'ex_standing_leg_curl',
    name: 'Standing Single-Leg Curl',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: [],
    equipment: 'machine', movement: 'isolation', laterality: 'unilateral',
    muscleTargets: [...kneeHamstrings()],
  },
  {
    id: 'ex_single_leg_rdl',
    name: 'Single-Leg Romanian Deadlift',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes', 'back'],
    equipment: 'dumbbell', movement: 'compound', laterality: 'unilateral',
    muscleTargets: [...hipHamstrings(), ...secondary('gluteus_maximus', 'erector_spinae'), ...secondary('gluteus_medius')],
    biasNotes: 'Hip extension loads the long head of biceps femoris, semitendinosus and semimembranosus; the short head does not cross the hip.',
  },
  {
    id: 'ex_rdl_db',
    name: 'Dumbbell Romanian Deadlift',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes', 'back'],
    equipment: 'dumbbell', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...hipHamstrings(), ...secondary('gluteus_maximus', 'erector_spinae')],
    biasNotes: 'Hip extension loads the long head of biceps femoris, semitendinosus and semimembranosus; the short head does not cross the hip.',
  },
  {
    id: 'ex_nordic_curl',
    name: 'Nordic Hamstring Curl',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: [],
    equipment: 'bodyweight', movement: 'isolation', laterality: 'bilateral',
    muscleTargets: [...kneeHamstrings()],
    biasNotes: 'Knee flexion loads the hamstrings together; this entry does not assign exclusive semitendinosus or biceps femoris bias.',
  },
  {
    id: 'ex_good_morning',
    name: 'Barbell Good Morning',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes', 'back'],
    equipment: 'barbell', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...hipHamstrings(), ...secondary('gluteus_maximus', 'erector_spinae')],
    biasNotes: 'Hip extension loads the long head of biceps femoris, semitendinosus and semimembranosus; the short head does not cross the hip.',
  },
  {
    id: 'ex_glute_kickback_cable',
    name: 'Cable Glute Kickback',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings'],
    equipment: 'cable', movement: 'isolation', laterality: 'unilateral',
    muscleTargets: [...biased('gluteus_maximus'), ...hipHamstrings('secondary')],
  },
  {
    id: 'ex_hip_abduction_machine',
    name: 'Hip Abduction Machine',
    primaryMuscle: 'glutes',
    secondaryMuscles: [],
    equipment: 'machine', movement: 'isolation', laterality: 'bilateral',
    muscleTargets: [...biased('gluteus_medius', 'gluteus_minimus')],
    biasNotes: 'Hip abduction emphasizes gluteus medius and minimus together; the seated position and technique affect contribution.',
  },
  {
    id: 'ex_hip_abduction_cable',
    name: 'Cable Hip Abduction',
    primaryMuscle: 'glutes',
    secondaryMuscles: [],
    equipment: 'cable', movement: 'isolation', laterality: 'unilateral',
    muscleTargets: [...biased('gluteus_medius', 'gluteus_minimus')],
  },
  {
    id: 'ex_glute_bridge',
    name: 'Glute Bridge',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings'],
    equipment: 'bodyweight', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...biased('gluteus_maximus'), ...hipHamstrings('secondary')],
  },
  {
    id: 'ex_single_leg_hip_thrust',
    name: 'Single-Leg Hip Thrust',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings'],
    equipment: 'bodyweight', movement: 'compound', laterality: 'unilateral',
    muscleTargets: [...biased('gluteus_maximus'), ...primary('gluteus_medius'), ...hipHamstrings('secondary')],
  },
  {
    id: 'ex_hip_adduction_machine',
    name: 'Hip Adduction Machine',
    primaryMuscle: 'adductors',
    secondaryMuscles: [],
    equipment: 'machine', movement: 'isolation', laterality: 'bilateral',
    muscleTargets: [...adductors()],
    biasNotes: 'The hip adductors work together; this entry does not claim selective isolation of the individual muscles.',
  },
  {
    id: 'ex_hip_adduction_cable',
    name: 'Cable Hip Adduction',
    primaryMuscle: 'adductors',
    secondaryMuscles: [],
    equipment: 'cable', movement: 'isolation', laterality: 'unilateral',
    muscleTargets: [...adductors()],
  },
  {
    id: 'ex_side_lying_hip_adduction',
    name: 'Side-Lying Hip Adduction',
    primaryMuscle: 'adductors',
    secondaryMuscles: [],
    equipment: 'bodyweight', movement: 'isolation', laterality: 'unilateral',
    muscleTargets: [...adductors()],
  },
  {
    id: 'ex_standing_calf_raise',
    name: 'Standing Calf Raise',
    primaryMuscle: 'calves',
    secondaryMuscles: [],
    equipment: 'machine', movement: 'isolation', laterality: 'bilateral',
    muscleTargets: [...biased('gastrocnemius_medial_head', 'gastrocnemius_lateral_head'), ...primary('soleus')],
    biasNotes: 'A straight knee maintains gastrocnemius length. Both gastrocnemius heads and soleus work; foot angle is not used to claim head isolation.',
  },
  {
    id: 'ex_seated_calf_raise',
    name: 'Seated Calf Raise',
    primaryMuscle: 'calves',
    secondaryMuscles: [],
    equipment: 'machine', movement: 'isolation', laterality: 'bilateral',
    muscleTargets: [...biased('soleus'), ...primary('gastrocnemius_medial_head', 'gastrocnemius_lateral_head')],
    biasNotes: 'A bent knee reduces gastrocnemius contribution, giving soleus a relative emphasis; this does not imply greater soleus growth than standing raises.',
  },
  {
    id: 'ex_leg_press_calf_raise',
    name: 'Leg Press Calf Raise',
    primaryMuscle: 'calves',
    secondaryMuscles: [],
    equipment: 'machine', movement: 'isolation', laterality: 'bilateral',
    muscleTargets: [...biased('gastrocnemius_medial_head', 'gastrocnemius_lateral_head'), ...primary('soleus')],
    biasNotes: 'With knees mostly straight, both gastrocnemius heads work alongside the soleus.',
  },
  {
    id: 'ex_single_leg_calf_raise',
    name: 'Single-Leg Dumbbell Calf Raise',
    primaryMuscle: 'calves',
    secondaryMuscles: [],
    equipment: 'dumbbell', movement: 'isolation', laterality: 'unilateral',
    muscleTargets: [...biased('gastrocnemius_medial_head', 'gastrocnemius_lateral_head'), ...primary('soleus')],
  },
  {
    id: 'ex_tibialis_raise',
    name: 'Tibialis Raise',
    primaryMuscle: 'shins',
    secondaryMuscles: [],
    equipment: 'bodyweight', movement: 'isolation', laterality: 'bilateral',
    muscleTargets: [...biased('tibialis_anterior')],
    biasNotes: 'Ankle dorsiflexion trains the shin; it is tracked separately from the plantar-flexing calf muscles.',
  },
  {
    id: 'ex_cable_crunch',
    name: 'Cable Crunch',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: 'cable', movement: 'isolation', laterality: 'bilateral',
    muscleTargets: [...biased('rectus_abdominis'), ...primary('external_obliques', 'internal_obliques')],
    biasNotes: 'Trunk flexion emphasizes rectus abdominis; upper and lower abs are not treated as separate muscles.',
  },
  {
    id: 'ex_reverse_crunch',
    name: 'Reverse Crunch',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight', movement: 'isolation', laterality: 'bilateral',
    muscleTargets: [...biased('rectus_abdominis'), ...primary('external_obliques', 'internal_obliques')],
    biasNotes: 'Curling the pelvis toward the ribs trains rectus abdominis; it does not isolate a separate lower-ab muscle.',
  },
  {
    id: 'ex_hanging_knee_raise',
    name: 'Hanging Knee Raise',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...biased('rectus_abdominis'), ...primary('external_obliques', 'internal_obliques')],
    biasNotes: 'Includes a pelvic curl to train the abs; lifting only at the hips shifts work toward the hip flexors.',
  },
  {
    id: 'ex_ab_wheel_rollout',
    name: 'Ab Wheel Rollout',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: 'other', movement: 'compound', laterality: 'bilateral',
    muscleTargets: [...primary('rectus_abdominis', 'external_obliques', 'internal_obliques', 'transversus_abdominis')],
    biasNotes: 'The abdominal wall works together to resist spinal extension; deep-core activity is not an isolated measurement.',
  },
  {
    id: 'ex_dead_bug',
    name: 'Dead Bug',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight', movement: 'compound', laterality: 'either',
    muscleTargets: [...primary('rectus_abdominis', 'external_obliques', 'internal_obliques', 'transversus_abdominis')],
    biasNotes: 'The abdominal wall shares bracing work as the limbs move; count controlled repetitions.',
  },
  {
    id: 'ex_cable_woodchop',
    name: 'Cable Woodchop',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: 'cable', movement: 'compound', laterality: 'unilateral',
    muscleTargets: [...biased('external_obliques', 'internal_obliques'), ...primary('rectus_abdominis', 'transversus_abdominis')],
    biasNotes: 'Controlled trunk rotation emphasizes both oblique layers; left/right loading depends on the direction.',
  },
  {
    id: 'ex_pallof_press',
    name: 'Pallof Press',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: 'cable', movement: 'compound', laterality: 'unilateral',
    muscleTargets: [...biased('external_obliques', 'internal_obliques'), ...primary('transversus_abdominis', 'rectus_abdominis')],
    biasNotes: 'Anti-rotation challenges the abdominal wall; log press-out repetitions rather than hold duration.',
  },
];
